**Case Study - Insurance Claim Records using numpy**

Consider an insurance comapany analyzing monthly claims made by policyholders:

In [1]:
import numpy as np

In [2]:
# Monthly claim amounts (IN INR) for diffrent policyholders
claims = np.array([
    [12000,15000,18000], #policyholder 1
    [10000,13000,17000], #policyholder 2
    [9000,11000,16000]   #policyholder 3
])

print("Insurance Claim Data")
print(claims)

Insurance Claim Data
[[12000 15000 18000]
 [10000 13000 17000]
 [ 9000 11000 16000]]


In [4]:
# Accessing element in NDArray
# Access claim amount of policyholder 3 for the first month

print("Claim amount of policyholder 3 for 1 month : ", claims[2,0])
print("Claim amount of policyholder 2 for 3 month : ", claims[1,2])

Claim amount of policyholder 3 for 1 month :  9000
Claim amount of policyholder 2 for 3 month :  17000


**Array Operation in Numpy**

In [5]:
# Total claim amount per policyholder

total_claims = np.sum(claims, axis=1) # 1 for row wise , 0 for column wise
print("Total claim per policy holder : ", total_claims)

Total claim per policy holder :  [45000 40000 36000]


In [6]:
# Average claim amount per months

avg_claim = np.average(claims, axis=0)
print("Average claim amount per months are : ", avg_claim)

Average claim amount per months are :  [10333.33333333 13000.         17000.        ]


In [7]:
# Find claims greater than 15000

high_claims = claims[claims > 15000]
print("High vlue Claims : ",high_claims)

High vlue Claims :  [18000 17000 16000]
