In [2]:
import numpy as np

In [1]:
!pip install numpy

In [3]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
arr_index = arr[6]
arr_index

np.int64(7)

In [4]:
arr_slicing = arr[3::2]
arr_slicing

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr1 = np.arange(1,31).reshape(6,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [6]:
arr1[2]

array([11, 12, 13, 14, 15])

In [7]:
arr1[0,4] #[row, column]

np.int64(5)

In [8]:
arr1[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [9]:
arr1[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [10]:
arr1[:,2]

array([ 3,  8, 13, 18, 23, 28])

Boolean Indexing

In [11]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [13]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])