In [1]:
import numpy as np
from parso.parser import Stack

Arithmetic Operations -> Size must be same for both the arrays for performing operations

In [2]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
# arr1
# arr2

In [3]:
arr = arr1 + arr2
arr

array([ 7,  9, 11, 13, 15])

In [4]:
arr1 * arr2

array([ 6, 14, 24, 36, 50])

In [5]:
arr2 - arr1

array([5, 5, 5, 5, 5])

In [6]:
arr1 ** arr2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [7]:
l = [1,2,3,54,6]
arr = np.array(l)

In [8]:
arr + 10

array([11, 12, 13, 64, 16])

In [9]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and shallow copy

1 . shallow copy

In [11]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [12]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [13]:
slice = slice * 10

In [14]:
slice

array([10, 20, 30, 40, 50])

In [15]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
a[4:6] * 10

array([50, 60])

In [17]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
a
b = a.copy()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [21]:
m1 = np.arange(1,5).reshape(2,2)
m2 = np.arange(5,9).reshape(2,2)

In [22]:
m1

array([[1, 2],
       [3, 4]])

In [23]:
m2

array([[5, 6],
       [7, 8]])

In [24]:
m1 @ m2 #matrix multiplication

array([[19, 22],
       [43, 50]])

In [25]:
np.dot(m1,m2)

array([[19, 22],
       [43, 50]])

In [26]:
m1

array([[1, 2],
       [3, 4]])

In [27]:
m1.T  #Transpose

array([[1, 3],
       [2, 4]])

Advance array Manipulation

1. Stacking Array

In [28]:
m1

array([[1, 2],
       [3, 4]])

In [29]:
m2

array([[5, 6],
       [7, 8]])

In [30]:
# You can not stack two matrix

In [31]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [32]:
#There are three type of stack
# 1 . Vertical Stack
np.vstack((a,b))

# 2. Horizontal Stack
np.hstack((a,b))

# 3. Column stack
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

Splitting array

In [33]:
c = np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
# Horizontal Split
np.hsplit(c,2)

# Vertical Split
d = np.vsplit(c,4)

for i in d:
    print(i)


[[1 2 3 4]]
[[5 6 7 8]]
[[ 9 10 11 12]]
[[13 14 15 16]]
