Valid Sudoku


In [1]:
import numpy as np

In [2]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

s



array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [3]:
srow = np.sum(s,axis = 1)
for i in srow:
    if i!=45:
        print("Sudoku is not valid")
        break
else:
    print("For rows it is valid")

For rows it is valid


In [4]:
scol = np.sum(s, axis = 0)
for i in scol:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("Sudoku is valid for columns")


Sudoku is valid for columns


In [5]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


General Questions

In [6]:
import numpy as np
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

#Get the shape of the matrix.


In [7]:
data.shape

(5, 3)

#Find the average age of students.


In [8]:
np.mean(data[:,0])

np.float64(18.4)

#Extract Math marks of all students.


In [9]:
data[:,1]

array([85, 92, 76, 65, 90])

#Find the highest Science mark.


In [10]:
np.max(data[:,2])

np.int64(95)

#Get details of the student who scored more than 90 in Math.

In [11]:
data[data[:,1] > 90]

array([[19, 92, 88]])

#Increase Math marks of all students by 5.


In [12]:
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

#Find how many students are younger than 19.


In [13]:
len(data[data[:,0] < 19])

3

#Calculate the average marks in each subject (column-wise mean).


In [14]:
np.mean(data[:,1:],axis=0)


array([86.6, 83.2])

#Get data of students who scored at least 80 in both subjects.


In [15]:
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [16]:
data[:,2][data[:,2] < 75] = 0
data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])