In [8]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy as np

Some basic Array Creation

In [10]:
arr = np.array([1,2,3,4,0.5])
arr

array([1. , 2. , 3. , 4. , 0.5])

In [11]:
lis = [1,2,3,4,"Hello"]
lis

[1, 2, 3, 4, 'Hello']

Vectors -> Creates in One Dimensional
Metrix -> create in multi Dimensional

In [12]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Functions

In [14]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr = np.ones(1)
arr

array([1.])

In [17]:
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Random Generation function

In [18]:
arr = np.random.rand(5)
arr

array([0.1955653 , 0.82324731, 0.3370493 , 0.84599423, 0.16419305])

In [19]:
arr = np.random.randn(3)
arr

array([-1.18317105,  0.0590812 ,  0.10772266])

In [20]:
arr1 = np.random.randint(6) #it will generate the 6 random integer
arr2 = np.random.randint(6,10) #it will generate the random integer between 6,10
arr3 = np.random.randint(10,30,10) #it will generate the array of 2 random integer between 6,10
print(arr1)
print(arr2)
print(arr3)

3
9
[28 11 27 13 17 25 27 13 23 16]


Array Attributes -> variable defined inside the class
VS
Methods -> Methods defined inside the class

In [21]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.shape

(3, 3)

In [23]:
arr.size

9

In [24]:
arr.dtype

dtype('int64')

Array Methods

In [25]:
arr.min()

np.int64(1)

In [26]:
arr.max()

np.int64(9)

In [27]:
arr.sum()

np.int64(45)

In [28]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.sum(arr,axis=0)
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [29]:
arr.mean()

np.float64(5.0)

In [30]:
arr.std()

np.float64(2.581988897471611)

In [31]:
arr.argmax()

np.int64(8)

In [32]:
arr.argmin()

np.int64(0)

### **Reshaping and Resizing -----**

In [33]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [34]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [35]:
arr = np.empty((2,2))

In [36]:
arr

array([[0.25, 0.5 ],
       [0.75, 1.  ]])