In [2]:
!pip install numpy

  Using cached numpy-2.4.4-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.4-cp314-cp314-win_amd64.whl (12.4 MB)



[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

Some basic Array Creation

In [11]:
arr = np.array([1,2,3,4,0.5])
arr

array([1. , 2. , 3. , 4. , 0.5])

In [8]:
lis = [1,2,3,4,"Hello"]
lis

[1, 2, 3, 4, 'Hello']

Vectors -> Creates in One Dimensional
Metrix -> create in multi Dimensional

In [12]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Functions

In [17]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
arr = np.ones(1)
arr

array([1.])

In [28]:
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Random Generation function

In [31]:
arr = np.random.rand(5)
arr

array([0.31550284, 0.27577826, 0.10389141, 0.62332688, 0.41837695])

In [54]:
arr = np.random.randn(3)
arr

array([-0.01903012, -1.23935999, -0.43030909])

In [94]:
arr1 = np.random.randint(6) #it will generate the 6 random integer
arr2 = np.random.randint(6,10) #it will generate the random integer between 6,10
arr3 = np.random.randint(10,30,10) #it will generate the array of 2 random integer between 6,10
print(arr1)
print(arr2)
print(arr3)

1
6
[19 22 14 22 19 13 18 26 25 20]


Array Attributes -> variable defined inside the class
VS
Methods -> Methods defined inside the class

In [97]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
arr.shape

(3, 3)

In [99]:
arr.size

9

In [100]:
arr.dtype

dtype('int64')

Array Methods

In [101]:
arr.min()

np.int64(1)

In [103]:
arr.max()

np.int64(9)

In [104]:
arr.sum()

np.int64(45)

In [111]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.sum(arr,axis=0)
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [112]:
arr.mean()

np.float64(5.0)

In [113]:
arr.std()

np.float64(2.581988897471611)

In [114]:
arr.argmax()

np.int64(8)

In [115]:
arr.argmin()

np.int64(0)

### **Reshaping and Resizing -----**

In [16]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [17]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [5]:
arr = np.empty((2,2))

In [7]:
arr

array([[0.00000000e+000, 7.95212974e-312],
       [7.95212973e-312, 7.95212973e-312]])